server:
  port: 8086

spring:
  application:
    name: messaging-service
  datasource:
    url: jdbc:postgresql://localhost:5434/fyn_messages
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
